-- 코드를 입력하세요
SELECT b.BOOK_ID, a.AUTHOR_NAME, DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
FROM (SELECT BOOK_ID, AUTHOR_ID, PUBLISHED_DATE
     FROM BOOK WHERE CATEGORY = '경제') b
LEFT JOIN AUTHOR a
ON b.AUTHOR_ID = a.AUTHOR_ID
ORDER BY PUBLISHED_DATE;